name: edp
channels:
- defaults
dependencies:
- flask=0.12.2=py35_0
- pip=9.0.1=py35_1
- python=3.5.2=0
- sqlalchemy=1.1.11=py35_0
- psycopg2=2.7.1=py35_0
- pip:
  - flask-migrate==2.1.0
  - flask-script==2.0.5
  - flask-cors==3.0.3
